{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from {{cookiecutter.app_name}}.database import Column, Model, SurrogatePK, db, reference_col, relationship
from {{cookiecutter.app_name}}.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.Binary(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(FlaskForm):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/__init__.py
"""Main application package."""

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/app.py
# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from flask import Flask, render_template
from config import Config
from {{cookiecutter.app_name}} import public, user
from {{cookiecutter.app_name}}.extensions import bcrypt, cache, csrf_protect, db, login_manager, migrate


def create_app(config_class=Config):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.
    :param config_object: The configuration object to use.
    """
    app = Flask(__name__.split('.')[0])
    app.config.from_object(Config)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    register_shellcontext(app)
    return app


def register_extensions(app):
    """Register Flask extensions."""
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    migrate.init_app(app, db)
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None


def register_shellcontext(app):
    """Register shell context objects."""
    def shell_context():
        """Shell context objects."""
        return {
            'db': db,
            'User': user.models.User}

    app.shell_context_processor(shell_context)

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, url_for
from flask_login import login_required
from config import Config
blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

@blueprint.route('/map/', methods=['GET'])
def maps():
    """map"""
    c = Config()
    return render_template('users/maps.html', title = 'Map', LEEFLET_ACCESS_TOKEN=c.LEEFLET_ACCESS_TOKEN )

@blueprint.route('/table/', methods=['GET'])
def table():
    """table"""
    return render_template('users/table.html', title = 'Table')

@blueprint.route('/dashboard/', methods=['GET', 'POST'])
def dashboard():
    """dashboard"""
    return render_template('users/dashboard.html', title = 'Dashboard')

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/401.html
{% raw %}
{% extends "basic.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/basic.html
{% raw %}
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="../static/image/png" href="../static/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Animation library for notifications   -->
    <link href="../static/css/animate.min.css" rel="stylesheet" />
    <!--  Light Bootstrap Table core CSS    -->
    <link href="../static/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../static/css/pe-icon-7-stroke.css" rel="stylesheet" />
    {% block css %}{% endblock %}
</head>
<body>
    {% with form=form  %}
    {% endwith %}
    <div class="wrapper">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
            <div class="col-md-12">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                    {{message}}
                </div><!-- end .alert -->
                {% endfor %}
            </div><!-- end col-md -->
        </div><!-- end row -->
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </div>
    <!--   Core JS Files   -->
    <script src="../static/js/jquery.3.2.1.min.js" type="text/javascript"></script>
    <script src="../static/js/bootstrap.min.js" type="text/javascript"></script>
    <!--  Notifications Plugin    -->
    <script src="../static/js/bootstrap-notify.js"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
    <script src="../static/js/light-bootstrap-dashboard.js?v=1.4.0"></script>
    {% block js_main %}{% endblock %}
</body>

</html>
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/footer.html
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="#">
                        Home
                    </a>
                </li>

            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy;
            <script>document.write(new Date().getFullYear())</script> {{ cookiecutter.project_name }}
        </p>
    </div>
</footer>

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/layout.html
{% raw %}

  {% extends "basic.html" %}

  {% block content %}
  {% with links=True %}
  {% include "sidebar.html" %}
  {% endwith %}
  <div class="main-panel">

  {% with links=True %}
  {% include "navbar.html" %}
  {% endwith %}

      {% block layout_content %}{% endblock %}
      {% include "footer.html" %}
  </div>
  {% endblock %}

  {% block js_main %}

  




  {% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/navbar.html
<nav class="navbar navbar-default navbar-fixed">
    {% raw %}
        {% if links %}
            {% include "navbar_links.html" %}
        {% endif %}
    {% endraw %} 
</nav>

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/navbar_links.html
{% raw %}
<div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="">
                                        {% if title %}
                                        {{ title }}
                                        {% else %}
                                        {% endraw %}
                                        {{ cookiecutter.project_name }}
                                        {% raw %}
                                        {% endif %}
                                        </a>
    </div>
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!--  <i class="fa fa-dashboard"></i> -->
                </a>
            </li>
        </ul>
    </div>
</div>
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/sidebar.html
<div class="sidebar" data-color="{{ cookiecutter.sidebar_color }}" data-image="../static/img/sidebar-5.jpg">

    <!--

        Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
        Tip 2: you can also add an image using data-image tag

    -->

    <div class="sidebar-wrapper">
        <div class="logo">
            {{ cookiecutter.project_name }}
        </div>
        {% raw %}
            {% if links %}
                {% include "sidebar_links.html" %}
            {% endif %}
        {% endraw %} 
    </div>
</div>

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/sidebar_links.html
{% raw %}
<ul class="nav">
    <li class="active">
        <a href="{{ url_for('public.home') }}">
            <i class="pe-7s-home"></i>
            <p>Home</p>
        </a>
    </li>
    <li class="active">
        <a href="{{ url_for('user.maps') }}">
            <i class="pe-7s-map"></i>
            <p>Map</p>
        </a>
    </li>
    <li class="active">
        <a href="{{ url_for('user.table') }}">
            <i class="pe-7s-menu"></i>
            <p>Table</p>
        </a>
    </li>
    <li class="active">
        <a href="{{ url_for('user.dashboard') }}">
            <i class="pe-7s-graph3"></i>
            <p>Dashboard</p>
        </a>
    </li>

</ul>
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/template.html
{% raw %}
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta charset="utf-8" />
    <link rel="icon" type="../static/image/png" href="../static/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>
        {% block page_title %}
        {% endraw %}
        {{ cookiecutter.project_name }}
        {% raw %}
        {% endblock %}
    </title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../static/css/animate.min.css" rel="stylesheet" />

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../static/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../static/css/pe-icon-7-stroke.css" rel="stylesheet" />


    {% block css %}{% endblock %}
</head>
<body>
    
    {% with form=form  %}
    {% endwith %}
    <header>{% block header %}{% endblock %}</header>
    <main role="main">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="row">
            <div class="col-md-12">
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
                    {{message}}
                </div><!-- end .alert -->
                {% endfor %}
            </div><!-- end col-md -->
        </div><!-- end row -->
        {% endif %}
        {% endwith %}
        <div class="wrapper">

            {% include "sidebar.html" %}

            <div class="main-panel">
                {% include "navbar.html" %}


                {% block content %}{% endblock %}


                {% include "footer.html" %}

            </div>
        </div>

</body>

<!--   Core JS Files   -->
<script src="../static/js/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../static/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="../static/js/chartist.min.js"></script>

<!--  Notifications Plugin    -->
<script src="../static/js/bootstrap-notify.js"></script>

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

<!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="../static/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="../static/js/demo.js"></script>


</html>
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/users/dashboard.html
{% raw %}
{% extends "layout.html" %}
{% block layout_content %}
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <div class="card">

                    <div class="header">
                        <h4 class="title">Email Statistics</h4>
                        <p class="category">Last Campaign Performance</p>
                    </div>
                    <div class="content">
                        <div id="chartPreferences" class="ct-chart ct-perfect-fourth"></div>

                        <div class="footer">
                            <div class="legend">
                                <i class="fa fa-circle text-info"></i> Open
                                <i class="fa fa-circle text-danger"></i> Bounce
                                <i class="fa fa-circle text-warning"></i> Unsubscribe
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="fa fa-clock-o"></i> Campaign sent 2 days ago
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Users Behavior</h4>
                        <p class="category">24 Hours performance</p>
                    </div>
                    <div class="content">
                        <div id="chartHours" class="ct-chart"></div>
                        <div class="footer">
                            <div class="legend">
                                <i class="fa fa-circle text-info"></i> Open
                                <i class="fa fa-circle text-danger"></i> Click
                                <i class="fa fa-circle text-warning"></i> Click Second Time
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="fa fa-history"></i> Updated 3 minutes ago
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <div class="row">
            <div class="col-md-6">
                <div class="card ">
                    <div class="header">
                        <h4 class="title">2014 Sales</h4>
                        <p class="category">All products including Taxes</p>
                    </div>
                    <div class="content">
                        <div id="chartActivity" class="ct-chart"></div>

                        <div class="footer">
                            <div class="legend">
                                <i class="fa fa-circle text-info"></i> Tesla Model S
                                <i class="fa fa-circle text-danger"></i> BMW 5 Series
                            </div>
                            <hr>
                            <div class="stats">
                                <i class="fa fa-check"></i> Data information certified
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card ">
                    <div class="header">
                        <h4 class="title">Tasks</h4>
                        <p class="category">Backend development</p>
                    </div>
                    <div class="content">
                        <div class="table-full-width">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td>
											<div class="checkbox">
						  							 <input id="checkbox1" type="checkbox">
						  							 <label for="checkbox1"></label>
					  						  		</div>
                                        </td>
                                        <td>Sign contract for "What are conference organizers afraid of?"</td>
                                        <td class="td-actions text-right">
                                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
													<div class="checkbox">
						  							  	<input id="checkbox2" type="checkbox" checked>
						  							  	<label for="checkbox2"></label>
					  						  		</div>
                                        </td>
                                        <td>Lines From Great Russian Literature? Or E-mails From My Boss?</td>
                                        <td class="td-actions text-right">
                                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
													<div class="checkbox">
						  							  	<input id="checkbox3" type="checkbox">
						  							  	<label for="checkbox3"></label>
					  						  		</div>
                                        </td>
                                        <td>Flooded: One year later, assessing what was lost and what was found when a ravaging rain swept through metro Detroit
												</td>
                                        <td class="td-actions text-right">
                                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
													<div class="checkbox">
						  							  	<input id="checkbox4" type="checkbox" checked>
						  							  	<label for="checkbox4"></label>
					  						  		</div>
                                        </td>
                                        <td>Create 4 Invisible User Experiences you Never Knew About</td>
                                        <td class="td-actions text-right">
                                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
													<div class="checkbox">
						  							  	<input id="checkbox5" type="checkbox">
						  							  	<label for="checkbox5"></label>
					  						  		</div>
                                        </td>
                                        <td>Read "Following makes Medium better"</td>
                                        <td class="td-actions text-right">
                                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
													<div class="checkbox">
						  							  	<input id="checkbox6" type="checkbox" checked>
						  							  	<label for="checkbox6"></label>
					  						  		</div>
                                        </td>
                                        <td>Unfollow 5 enemies from twitter</td>
                                        <td class="td-actions text-right">
                                            <button type="button" rel="tooltip" title="Edit Task" class="btn btn-info btn-simple btn-xs">
                                                <i class="fa fa-edit"></i>
                                            </button>
                                            <button type="button" rel="tooltip" title="Remove" class="btn btn-danger btn-simple btn-xs">
                                                <i class="fa fa-times"></i>
                                            </button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <div class="footer">
                            <hr>
                            <div class="stats">
                                <i class="fa fa-history"></i> Updated 3 minutes ago
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_main %}
<!--  Charts Plugin -->
<script src="../static/js/chartist.min.js"></script>

<script type="text/javascript">
    	$(document).ready(function(){

        	demo.initChartist();

        	$.notify({
            	icon: 'pe-7s-gift',
            	message: "Welcome to <b>Light Bootstrap Dashboard</b> - a beautiful freebie for every web developer."

            },{
                type: 'info',
                timer: 4000
            });

    	});
	</script>



<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="../static/js/demo.js"></script>
{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/users/maps.html
{% raw %}
{% extends "layout.html" %}
{% block css %}
 <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA==" crossorigin=""/>
{% endblock %}
{% block layout_content %}
    <div id="mapid" style= "height:100%"></div>
{% endblock %}
{% block js_custom %}
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js" integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg==" crossorigin=""></script>
<script type="text/javascript">
    	var streets = L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
				maxZoom: 18,
				id: 'mapbox.streets',
				accessToken: "{{ LEEFLET_ACCESS_TOKEN }}"
		})

		// Create map
		var mymap = L.map('mapid',{
				center: [46.271,-115.396 ],
				zoom: 5,
				layers:[streets]
		})

</script>

{% endblock %}
{% endraw %}

{{cookiecutter.app_name}}/{{cookiecutter.app_name}}/templates/users/members.html
{% raw %}
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1>Welcome {{ current_user.username }}</h1>
        <h3>This is the members-only page.</h3>
    </div>
{% endblock %}
{% endraw%}